[package]
name = "dicemind-cli"
version = "0.0.0"
default-run = "dicemind-cli"
edition = "2021"

[dependencies]
clap = "4.4.18"
dicemind = { path = "../dicemind" }
textplots = "0.8.5"
rayon = "1.8.1"
human-panic = { version = "1.2.3", features = ["nightly"] }
rustyline = "13.0.0"
